-- MySQL Script generated by MySQL Workbench
-- Sun Jun  5 19:57:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Daniel_Rodriguez
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Daniel_Rodriguez
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Daniel_Rodriguez` DEFAULT CHARACTER SET utf8 ;
USE `Daniel_Rodriguez` ;

-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `price` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Title` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `schoolsId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Title_Schools1_idx` (`schoolsId` ASC),
  CONSTRAINT `fk_Title_Schools1`
    FOREIGN KEY (`schoolsId`)
    REFERENCES `Daniel_Rodriguez`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Internships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Internships` (
  `id` INT NOT NULL,
  `nameCompany` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Grade` (
  `id` INT NOT NULL,
  `name` TINYTEXT NOT NULL,
  `optional` TINYINT NOT NULL,
  `Student_id` INT NOT NULL,
  `Title_id` INT NOT NULL,
  `Internships_id` INT NOT NULL,
  `Schools_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Student_id`, `Schools_id`),
  INDEX `fk_Asignature_Title1_idx` (`Title_id` ASC),
  INDEX `fk_Asignature_Internships1_idx` (`Internships_id` ASC),
  INDEX `fk_Assignature_Schools1_idx` (`Schools_id` ASC),
  CONSTRAINT `fk_Asignature_Title1`
    FOREIGN KEY (`Title_id`)
    REFERENCES `Daniel_Rodriguez`.`Title` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignature_Internships1`
    FOREIGN KEY (`Internships_id`)
    REFERENCES `Daniel_Rodriguez`.`Internships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Assignature_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `schoolTitle` TINYINT NOT NULL,
  `Asignature_id` INT NOT NULL,
  `Schools_id` INT NOT NULL,
  `Schools_Student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Schools_id`, `Schools_Student_id`),
  INDEX `fk_Teachers_Asignature1_idx` (`Asignature_id` ASC),
  INDEX `fk_Teachers_Schools1_idx` (`Schools_id` ASC, `Schools_Student_id` ASC),
  CONSTRAINT `fk_Teachers_Asignature1`
    FOREIGN KEY (`Asignature_id`)
    REFERENCES `Daniel_Rodriguez`.`Grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teachers_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Residence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Residence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Sports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sport` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `careerPercent` DECIMAL NOT NULL,
  `age` INT NOT NULL,
  `Residence_id` INT NOT NULL,
  `Schools_id` INT NOT NULL,
  `Schools_Student_id` INT NOT NULL,
  `Sports_id` INT NOT NULL,
  `Internships_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Student_Residence1_idx` (`Residence_id` ASC),
  INDEX `fk_Student_Schools1_idx` (`Schools_id` ASC, `Schools_Student_id` ASC),
  INDEX `fk_Student_Sports1_idx` (`Sports_id` ASC),
  INDEX `fk_Student_Internships1_idx` (`Internships_id` ASC),
  CONSTRAINT `fk_Student_Residence1`
    FOREIGN KEY (`Residence_id`)
    REFERENCES `Daniel_Rodriguez`.`Residence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Sports1`
    FOREIGN KEY (`Sports_id`)
    REFERENCES `Daniel_Rodriguez`.`Sports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Internships1`
    FOREIGN KEY (`Internships_id`)
    REFERENCES `Daniel_Rodriguez`.`Internships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` INT NULL,
  `date` DATE NOT NULL,
  `Asignature_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Exam_Asignature1_idx` (`Asignature_id` ASC),
  CONSTRAINT `fk_Exam_Asignature1`
    FOREIGN KEY (`Asignature_id`)
    REFERENCES `Daniel_Rodriguez`.`Grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Library` (
  `id` INT NOT NULL,
  `books` INT NOT NULL,
  `Schools_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Library_Schools1_idx` (`Schools_id` ASC),
  CONSTRAINT `fk_Library_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Grant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Grant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `percentage` INT NULL,
  `Student_id` INT NOT NULL,
  `Student_Schools_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Grant_Student1_idx` (`Student_id` ASC, `Student_Schools_id` ASC),
  CONSTRAINT `fk_Grant_Student1`
    FOREIGN KEY (`Student_id` , `Student_Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Student` (`id` , `Schools_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Sponsorship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Sponsorship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` TINYTEXT NULL,
  `Schools_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sponsorship_Schools1_idx` (`Schools_id` ASC),
  CONSTRAINT `fk_Sponsorship_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Researchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Researchs` (
  `idResearchs` INT NOT NULL,
  `Teachers_id` INT NOT NULL,
  `Sponsorship_id` INT NOT NULL,
  PRIMARY KEY (`idResearchs`),
  INDEX `fk_Researchs_Teachers1_idx` (`Teachers_id` ASC),
  INDEX `fk_Researchs_Sponsorship1_idx` (`Sponsorship_id` ASC),
  CONSTRAINT `fk_Researchs_Teachers1`
    FOREIGN KEY (`Teachers_id`)
    REFERENCES `Daniel_Rodriguez`.`Teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Researchs_Sponsorship1`
    FOREIGN KEY (`Sponsorship_id`)
    REFERENCES `Daniel_Rodriguez`.`Sponsorship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Exchanges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Exchanges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `procedency` TINYTEXT NOT NULL,
  `Student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Exchanges_Student1_idx` (`Student_id` ASC),
  CONSTRAINT `fk_Exchanges_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `Daniel_Rodriguez`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Student_has_Exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Student_has_Exam` (
  `Student_id` INT NOT NULL,
  `Exam_id` INT NOT NULL,
  `Exam_Asignature_id` INT NOT NULL,
  PRIMARY KEY (`Student_id`, `Exam_id`, `Exam_Asignature_id`),
  INDEX `fk_Student_has_Exam_Exam1_idx` (`Exam_id` ASC, `Exam_Asignature_id` ASC),
  INDEX `fk_Student_has_Exam_Student1_idx` (`Student_id` ASC),
  CONSTRAINT `fk_Student_has_Exam_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `Daniel_Rodriguez`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Exam_Exam1`
    FOREIGN KEY (`Exam_id` , `Exam_Asignature_id`)
    REFERENCES `Daniel_Rodriguez`.`Exam` (`id` , `Asignature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Teachers_has_Title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Teachers_has_Title` (
  `Teachers_id` INT NOT NULL,
  `Teachers_Schools_id` INT NOT NULL,
  `Teachers_Schools_Student_id` INT NOT NULL,
  `Title_id` INT NOT NULL,
  `Title_Schools_id` INT NOT NULL,
  PRIMARY KEY (`Teachers_id`, `Teachers_Schools_id`, `Teachers_Schools_Student_id`, `Title_id`, `Title_Schools_id`),
  INDEX `fk_Teachers_has_Title_Title1_idx` (`Title_id` ASC, `Title_Schools_id` ASC),
  INDEX `fk_Teachers_has_Title_Teachers1_idx` (`Teachers_id` ASC, `Teachers_Schools_id` ASC, `Teachers_Schools_Student_id` ASC),
  CONSTRAINT `fk_Teachers_has_Title_Teachers1`
    FOREIGN KEY (`Teachers_id` , `Teachers_Schools_id` , `Teachers_Schools_Student_id`)
    REFERENCES `Daniel_Rodriguez`.`Teachers` (`id` , `Schools_id` , `Schools_Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teachers_has_Title_Title1`
    FOREIGN KEY (`Title_id` , `Title_Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Title` (`id` , `schoolsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daniel_Rodriguez`.`Grade_has_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Daniel_Rodriguez`.`Grade_has_Student` (
  `Grade_id` INT NOT NULL,
  `Grade_Student_id` INT NOT NULL,
  `Grade_Schools_id` INT NOT NULL,
  `Student_id` INT NOT NULL,
  PRIMARY KEY (`Grade_id`, `Grade_Student_id`, `Grade_Schools_id`, `Student_id`),
  INDEX `fk_Grade_has_Student_Student1_idx` (`Student_id` ASC),
  INDEX `fk_Grade_has_Student_Grade1_idx` (`Grade_id` ASC, `Grade_Student_id` ASC, `Grade_Schools_id` ASC),
  CONSTRAINT `fk_Grade_has_Student_Grade1`
    FOREIGN KEY (`Grade_id` , `Grade_Student_id` , `Grade_Schools_id`)
    REFERENCES `Daniel_Rodriguez`.`Grade` (`id` , `Student_id` , `Schools_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grade_has_Student_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `Daniel_Rodriguez`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;